### ISSUE TITLE
refactor getMetadata

### ISSUE THREAD

**Issue by kdaily** [markdane/MEMA#18]
`getMetadata` relies heavily on folder structure. should factor out files to read in to a data structure (that depends if it's annot! or not) plus the flag for `useAnnotMetadata`. Something like:

```
getMetadata <- function (metadataFiles, useAnnotMetadata = TRUE) {
  if (useAnnotMetadata){
    metadata <- processan2omero(metadataFiles[['annotMetadata']])
    ....
  }
  else {
    ldf <- getLogMetadata(metadataFiles[['logMetadata']])
    ....
  }
```

Outside of the function is where you determine which files to use (which may or may not rely on folder structure).

**Comment by kdaily** [comment]
Think this is closed - @markdane please confirm, thanks!

**Comment by markdane** [comment]
yes, it's done.
